### ISSUE TITLE
[Bug] wishlist toggle

### ISSUE THREAD

**Issue by budi7** [chelsymooy/SKY-GL#2]
Mutation: ToggleWishlist

Expected : 
saat pertama kali mutation dijalankan akan menambahkan barang ke wishlist, apabila mutation yg sama di eksekusi lagi, akan menghapus barang dari daftar wishlist

What's wrong?
saat eksekusi mutation untuk kedua kali (menghapus produk dari wishlist), produk masih ada dan tidak terhapus

**Comment by chelsymooy** [comment]
**QUERY ADD WISHLIST**

mutation wlist{
  ToggleWishlist(product_code:"UPC-1" is_add:true) {
    product_code
  }
}

**Comment by chelsymooy** [comment]
**QUERY REMOVE WISHLIST** 


mutation wlist{
  ToggleWishlist(product_code:"UPC-1" is_add:false) {
    product_code
  }
}

**Comment by chelsymooy** [comment]
work fine
kalau ada ttp ke reload, coba refresh my wishlist
