### ISSUE TITLE
[Question] Query stock with warehouse data

### ISSUE THREAD

**Issue by budi7** [chelsymooy/SKY-GL#3]
what's wrong?
![image](https://user-images.githubusercontent.com/10555410/63008147-37b87a80-beac-11e9-9567-33e89fc00e8c.png)
Query stock with data warehouse returning error 500
![image](https://user-images.githubusercontent.com/10555410/63008257-72baae00-beac-11e9-9a4b-5099d00c9724.png)

**Comment by budi7** [comment]
curl

curl 'http://128.199.145.173:7888/graphql' -H 'accept: */*' -H 'Referer: http://localhost:3000/cart/checkout' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxMjMxMjMxMjMiLCJhdWQiOiIxMjMxMjMxMjMiLCJpYXQiOjE1NjU2ODA4NjksImV4cCI6MTU2ODI3Mjg2OSwibmFtZSI6IkJ1ZGkgUHVybm9tbyIsInVzZXJuYW1lIjoiMDgxMjM0NTY3ODkwIn0.aMgSv1WP19Lr2kmRT65277sBOHHTTc8g6D-Q9ZzKzYk' -H 'content-type: application/json' --data-binary '{"operationName":"stock","variables":{"products":["UPC-3","UPC-9","UPC-2","UPC-11","UPC-7","UPC-12","UPC-20","UPC-4"]},"query":"query stock($products: [String], $warehouse_id: [Int]) {\n  Stock(product_code: $products, warehouse_id: $warehouse_id) {\n    product_code\n    product_name\n    available\n    warehouse {\n      id\n      name\n      address\n      city\n      province\n      country\n      postcode\n      contact\n      __typename\n    }\n    __typename\n  }\n}\n"}' --compressed --insecure

**Comment by chelsymooy** [comment]
ADDITIONAL NOTES

Untuk menampilkan stock di warehouse tertentu dengan query ini;


query sto{
  Stock(warehouse_id:1){
    product_name
    warehouse{
      id
    }
  }
}

untuk menampilkan product di semua warehouse:


query sto{
  Stock(group_by_warehouse:true){
    product_name
    warehouse{
      id
    }
  }
}
